In [1]:
# ============================================================
# CadetX — Heavy Supplier, Inventory & Warehouse Analytics
# Notebook 01: Data Cleaning & Master Table Construction
# Week 1 — Foundation & Exploration
#
# Purpose: Load raw CSVs, join into 4 analysis-ready master
# tables, profile for data quality issues, and flag (not
# silently fix) anything requiring team decision.
#
# Author: Rita Orobosa Aiwuyo
# Date: 3rd sept 2026
# ============================================================

In [2]:
import pandas as pd
import numpy as np
import datetime as dt
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
import zipfile
with zipfile.ZipFile(r"C:\Users\LENOVO\OneDrive\Desktop\HeavySuppliersWarehouseDatasets.zip") as zip_ref:
    zip_ref.extractall('data')

In [4]:
import os
os.listdir('data')

['HeavySuppliersWarehouseDatasets']

In [5]:
import os
folder = 'data/HeavySuppliersWarehouseDatasets'
data={}
for filename in os.listdir(folder):
    if filename.endswith('.csv'):
        table_name= filename.replace('.csv', '')
        data[table_name] = pd.read_csv(f'{folder}/{filename}')
        print(f"Loaded {table_name} : {data[table_name].shape}")

Loaded branches : (6, 13)
Loaded customers : (500, 15)
Loaded inventory_master : (180, 8)
Loaded invoices : (18033, 10)
Loaded payments : (19257, 5)
Loaded products : (30, 23)
Loaded purchase_orders_header : (24000, 10)
Loaded purchase_orders_lines : (155495, 9)
Loaded sales_orders_header : (20000, 11)
Loaded sales_orders_lines : (130402, 9)
Loaded stock_ledger : (237230, 9)
Loaded suppliers : (8, 12)

In [6]:
data['products'].head()

,product_id,product_name,category,machine_type,brand,model_compatibility,unit_cost,unit_price,margin_percentage,gst_rate,...,warranty_months,reorder_level,safety_stock,max_stock_level,lead_time_days,criticality_level,usage_frequency,uom,last_purchase_price,last_purchase_date
0,P001,Hydraulic Pump HP-300,Hydraulic,Excavator,CAT,CAT 320D,18950,24500,29.2,28,...,12,15,10,40,21,High,Medium,piece,18500,2019-03-15
1,P002,Engine Oil Filter OF-90,Filters,Loader,JCB,JCB 3DX,450,720,37.3,18,...,6,80,40,200,7,Medium,High,piece,430,2019-07-22
2,P003,Air Filter AF-120,Filters,Excavator,Komatsu,Komatsu PC210,820,1250,52.4,18,...,6,60,30,150,7,Medium,High,piece,800,2020-01-10
3,P004,Track Chain TC-45,Undercarriage,Bulldozer,Volvo,Volvo D6,32500,39800,22.5,28,...,18,8,4,20,30,High,Low,set,32000,2020-06-18
4,P005,Fuel Injector FI-220,Engine,Excavator,Tata Hitachi,Tata Hitachi EX 200,6350,8450,33.0,28,...,12,30,15,80,18,High,Medium,piece,6200,2020-11-05

In [7]:
data['products'].sample(10)

,product_id,product_name,category,machine_type,brand,model_compatibility,unit_cost,unit_price,margin_percentage,gst_rate,...,warranty_months,reorder_level,safety_stock,max_stock_level,lead_time_days,criticality_level,usage_frequency,uom,last_purchase_price,last_purchase_date
21,P022,Control Valve CV-75,Hydraulic,Excavator,CAT,CAT 320D,12800,16900,32.0,28,...,12,10,5,30,18,High,Medium,piece,12500,2024-11-22
29,P030,Fuel Pump FP-350,Engine,Excavator,Volvo,Volvo EC210,16400,21900,33.5,28,...,12,10,5,25,18,High,Medium,piece,16000,2024-08-21
6,P007,Hydraulic Hose HH-60,Hydraulic,Crane,JCB,JCB 160,980,1450,48.0,18,...,6,70,35,200,10,Medium,High,piece,950,2021-05-27
1,P002,Engine Oil Filter OF-90,Filters,Loader,JCB,JCB 3DX,450,720,37.3,18,...,6,80,40,200,7,Medium,High,piece,430,2019-07-22
12,P013,Seal Kit SK-15,Seals,Excavator,CAT,CAT 320D,950,1450,52.6,18,...,6,80,40,200,9,Medium,High,set,920,2022-12-19
23,P024,Track Roller TR-60,Undercarriage,Bulldozer,Tata Hitachi,Tata Hitachi EX 200,7400,10300,39.2,28,...,12,8,4,22,22,High,Medium,piece,7200,2025-03-08
22,P023,Idler Wheel IW-55,Undercarriage,Bulldozer,Volvo,Volvo D6,9200,12950,40.8,28,...,12,6,3,18,20,High,Medium,piece,9000,2025-01-15
17,P018,Wheel Rim WR-24,Undercarriage,Bulldozer,CAT,CAT D6R,8200,11300,37.8,28,...,12,12,6,30,20,High,Medium,piece,8000,2024-02-20
8,P009,Starter Motor SM-700,Electrical,Dumper,Volvo,Volvo A40,11450,14900,30.1,28,...,12,10,5,25,22,High,Medium,piece,11000,2021-11-30
27,P028,Light Assembly LA-18,Electrical,Loader,Generic,JCB 3DX,1450,2250,55.2,18,...,6,40,20,100,9,Medium,Medium,piece,1380,2022-02-18

In [8]:
data['products'].dtypes

product_id              object
product_name            object
category                object
machine_type            object
brand                   object
model_compatibility     object
unit_cost                int64
unit_price               int64
margin_percentage      float64
gst_rate                 int64
weight_kg              float64
dimensions_cm           object
material_type           object
warranty_months          int64
reorder_level            int64
safety_stock             int64
max_stock_level          int64
lead_time_days           int64
criticality_level       object
usage_frequency         object
uom                     object
last_purchase_price      int64
last_purchase_date      object
dtype: object

In [9]:
data['products'].isnull().sum()

product_id             0
product_name           0
category               0
machine_type           0
brand                  0
model_compatibility    0
unit_cost              0
unit_price             0
margin_percentage      0
gst_rate               0
weight_kg              0
dimensions_cm          0
material_type          0
warranty_months        0
reorder_level          0
safety_stock           0
max_stock_level        0
lead_time_days         0
criticality_level      0
usage_frequency        0
uom                    0
last_purchase_price    0
last_purchase_date     0
dtype: int64

In [10]:
data['products'].shape

(30, 23)

In [11]:
data['branches'].head(10)

,branch_id,branch_name,city,state,region,warehouse_type,warehouse_capacity,service_center_available,manager_id,total_employees,avg_monthly_revenue,monthly_operational_cost,market_demand_index
0,DEL001,Delhi Central,Delhi,Delhi,North,Central,45230 sqft,Yes,9593,92,5234890,3189000,9
1,PUN001,Pune Distribution,Pune,Maharashtra,West,Regional,38750 sqft,Yes,6114,74,4389120,2654000,8
2,CHN001,Chennai South Hub,Chennai,Tamil Nadu,South,Regional,41890 sqft,Yes,7922,81,4567780,2739000,8
3,HYD001,Hyderabad Logistics,Hyderabad,Telangana,South,Branch,36210 sqft,No,4390,57,3102455,1887000,7
4,KOL001,Kolkata East Depot,Kolkata,West Bengal,East,Branch,29880 sqft,No,5981,49,2894770,1743000,6
5,AHM001,Ahmedabad West Hub,Ahmedabad,Gujarat,West,Service Hub,34120 sqft,Yes,4772,63,3245890,2018000,7

In [12]:
data['branches'].dtypes

branch_id                   object
branch_name                 object
city                        object
state                       object
region                      object
warehouse_type              object
warehouse_capacity          object
service_center_available    object
manager_id                   int64
total_employees              int64
avg_monthly_revenue          int64
monthly_operational_cost     int64
market_demand_index          int64
dtype: object

In [13]:
data['inventory_master'].head()

,product_id,branch_id,opening_stock,reorder_level,safety_stock,max_stock,current_stock,warehouse_bin
0,P001,DEL001,196,59,46,340,115928,C15
1,P001,PUN001,198,70,43,349,109389,D16
2,P001,CHN001,187,62,44,311,99373,A11
3,P001,HYD001,226,71,65,417,108772,A10
4,P001,KOL001,263,94,58,475,103808,F03

In [14]:
data['inventory_master'].sample(10)

,product_id,branch_id,opening_stock,reorder_level,safety_stock,max_stock,current_stock,warehouse_bin
4,P001,KOL001,263,94,58,475,103808,F03
93,P016,HYD001,103,35,24,177,106040,A01
128,P022,CHN001,138,44,31,227,109061,A02
81,P014,HYD001,200,71,50,377,111315,C17
179,P030,AHM001,134,46,40,231,103248,D06
161,P027,AHM001,151,51,33,294,108337,F10
24,P005,DEL001,242,94,63,463,110862,E03
57,P010,HYD001,171,62,46,307,110225,F12
115,P020,PUN001,80,24,16,140,102734,E12
138,P024,DEL001,280,99,56,469,116412,A17

In [15]:
data['inventory_master'].isnull().sum()

product_id       0
branch_id        0
opening_stock    0
reorder_level    0
safety_stock     0
max_stock        0
current_stock    0
warehouse_bin    0
dtype: int64

In [16]:
data['inventory_master'].dtypes

product_id       object
branch_id        object
opening_stock     int64
reorder_level     int64
safety_stock      int64
max_stock         int64
current_stock     int64
warehouse_bin    object
dtype: object

In [17]:
# Join inventory_master table to products table to form an inventory_health table. 

### Code ###
inventory_health = data['inventory_master'].merge(data['products'], on ='product_id', suffixes = ('_inv', '_prod'))
inventory_health.head(10)

,product_id,branch_id,opening_stock,reorder_level_inv,safety_stock_inv,max_stock,current_stock,warehouse_bin,product_name,category,...,warranty_months,reorder_level_prod,safety_stock_prod,max_stock_level,lead_time_days,criticality_level,usage_frequency,uom,last_purchase_price,last_purchase_date
0,P001,DEL001,196,59,46,340,115928,C15,Hydraulic Pump HP-300,Hydraulic,...,12,15,10,40,21,High,Medium,piece,18500,2019-03-15
1,P001,PUN001,198,70,43,349,109389,D16,Hydraulic Pump HP-300,Hydraulic,...,12,15,10,40,21,High,Medium,piece,18500,2019-03-15
2,P001,CHN001,187,62,44,311,99373,A11,Hydraulic Pump HP-300,Hydraulic,...,12,15,10,40,21,High,Medium,piece,18500,2019-03-15
3,P001,HYD001,226,71,65,417,108772,A10,Hydraulic Pump HP-300,Hydraulic,...,12,15,10,40,21,High,Medium,piece,18500,2019-03-15
4,P001,KOL001,263,94,58,475,103808,F03,Hydraulic Pump HP-300,Hydraulic,...,12,15,10,40,21,High,Medium,piece,18500,2019-03-15
5,P001,AHM001,236,77,53,455,106714,C20,Hydraulic Pump HP-300,Hydraulic,...,12,15,10,40,21,High,Medium,piece,18500,2019-03-15
6,P002,DEL001,166,57,35,261,108628,A06,Engine Oil Filter OF-90,Filters,...,6,80,40,200,7,Medium,High,piece,430,2019-07-22
7,P002,PUN001,113,41,27,180,101623,E01,Engine Oil Filter OF-90,Filters,...,6,80,40,200,7,Medium,High,piece,430,2019-07-22
8,P002,CHN001,267,102,76,465,105885,B04,Engine Oil Filter OF-90,Filters,...,6,80,40,200,7,Medium,High,piece,430,2019-07-22
9,P002,HYD001,219,78,64,383,121013,A02,Engine Oil Filter OF-90,Filters,...,6,80,40,200,7,Medium,High,piece,430,2019-07-22

In [18]:
inventory_health.shape

(180, 30)

In [19]:
inventory_health.isnull().sum()

product_id             0
branch_id              0
opening_stock          0
reorder_level_inv      0
safety_stock_inv       0
max_stock              0
current_stock          0
warehouse_bin          0
product_name           0
category               0
machine_type           0
brand                  0
model_compatibility    0
unit_cost              0
unit_price             0
margin_percentage      0
gst_rate               0
weight_kg              0
dimensions_cm          0
material_type          0
warranty_months        0
reorder_level_prod     0
safety_stock_prod      0
max_stock_level        0
lead_time_days         0
criticality_level      0
usage_frequency        0
uom                    0
last_purchase_price    0
last_purchase_date     0
dtype: int64

In [20]:
# join the inventory_health table to the branches table to form a full master table.
### code ###
inventory_health = inventory_health.merge(data['branches'], on = 'branch_id', suffixes = ('', '_branch'))
inventory_health.head()

,product_id,branch_id,opening_stock,reorder_level_inv,safety_stock_inv,max_stock,current_stock,warehouse_bin,product_name,category,...,state,region,warehouse_type,warehouse_capacity,service_center_available,manager_id,total_employees,avg_monthly_revenue,monthly_operational_cost,market_demand_index
0,P001,DEL001,196,59,46,340,115928,C15,Hydraulic Pump HP-300,Hydraulic,...,Delhi,North,Central,45230 sqft,Yes,9593,92,5234890,3189000,9
1,P001,PUN001,198,70,43,349,109389,D16,Hydraulic Pump HP-300,Hydraulic,...,Maharashtra,West,Regional,38750 sqft,Yes,6114,74,4389120,2654000,8
2,P001,CHN001,187,62,44,311,99373,A11,Hydraulic Pump HP-300,Hydraulic,...,Tamil Nadu,South,Regional,41890 sqft,Yes,7922,81,4567780,2739000,8
3,P001,HYD001,226,71,65,417,108772,A10,Hydraulic Pump HP-300,Hydraulic,...,Telangana,South,Branch,36210 sqft,No,4390,57,3102455,1887000,7
4,P001,KOL001,263,94,58,475,103808,F03,Hydraulic Pump HP-300,Hydraulic,...,West Bengal,East,Branch,29880 sqft,No,5981,49,2894770,1743000,6

In [21]:
inventory_health.shape

(180, 42)

In [22]:
inventory_health.isnull().sum()

product_id                  0
branch_id                   0
opening_stock               0
reorder_level_inv           0
safety_stock_inv            0
max_stock                   0
current_stock               0
warehouse_bin               0
product_name                0
category                    0
machine_type                0
brand                       0
model_compatibility         0
unit_cost                   0
unit_price                  0
margin_percentage           0
gst_rate                    0
weight_kg                   0
dimensions_cm               0
material_type               0
warranty_months             0
reorder_level_prod          0
safety_stock_prod           0
max_stock_level             0
lead_time_days              0
criticality_level           0
usage_frequency             0
uom                         0
last_purchase_price         0
last_purchase_date          0
branch_name                 0
city                        0
state                       0
region                      0
warehouse_type              0
warehouse_capacity          0
service_center_available    0
manager_id                  0
total_employees             0
avg_monthly_revenue         0
monthly_operational_cost    0
market_demand_index         0
dtype: int64

In [23]:
inventory_health.describe()

,opening_stock,reorder_level_inv,safety_stock_inv,max_stock,current_stock,unit_cost,unit_price,margin_percentage,gst_rate,weight_kg,...,reorder_level_prod,safety_stock_prod,max_stock_level,lead_time_days,last_purchase_price,manager_id,total_employees,avg_monthly_revenue,monthly_operational_cost,market_demand_index
count,180.000000,180.0000,180.000000,180.000000,180.000000,180.000000,180.000000,180.000000,180.000000,180.000000,...,180.000000,180.000000,180.000000,180.000000,180.000000,180.000000,180.000000,1.800000e+02,1.800000e+02,180.000000
mean,183.161111,64.5500,45.205556,321.755556,107240.366667,14585.000000,18593.666667,40.666667,23.666667,36.933333,...,39.733333,20.133333,104.833333,17.000000,14265.000000,6462.000000,69.333333,3.905818e+06,2.371667e+06,7.500000
std,63.441009,24.0554,16.873402,116.554283,5341.085645,21176.715802,26169.078621,15.836229,4.969179,78.195612,...,47.709269,24.197142,122.247140,9.150511,20800.871342,1804.858898,14.631412,8.724193e+05,5.239328e+05,0.960098
min,80.000000,24.0000,16.000000,131.000000,88853.000000,180.000000,310.000000,20.800000,18.000000,0.200000,...,3.000000,2.000000,8.000000,4.000000,170.000000,4390.000000,49.000000,2.894770e+06,1.743000e+06,6.000000
25%,129.000000,44.0000,31.000000,230.000000,103487.500000,950.000000,1450.000000,29.500000,18.000000,0.800000,...,8.000000,4.000000,22.000000,9.000000,920.000000,4772.000000,57.000000,3.102455e+06,1.887000e+06,7.000000
50%,178.500000,62.0000,43.500000,310.500000,107790.500000,7600.000000,10250.000000,36.700000,28.000000,7.900000,...,13.500000,8.000000,40.000000,18.000000,7400.000000,6047.500000,68.500000,3.817505e+06,2.336000e+06,7.500000
75%,234.500000,82.2500,58.000000,415.500000,110779.500000,18950.000000,24500.000000,52.400000,28.000000,24.000000,...,60.000000,30.000000,150.000000,22.000000,18500.000000,7922.000000,81.000000,4.567780e+06,2.739000e+06,8.000000
max,300.000000,119.0000,85.000000,582.000000,121013.000000,95500.000000,119000.000000,84.600000,28.000000,320.000000,...,200.000000,100.000000,500.000000,40.000000,94000.000000,9593.000000,92.000000,5.234890e+06,3.189000e+06,9.000000

In [24]:
inventory_health['CAUTION_current_stock_unreliable'] = (inventory_health['current_stock'] > inventory_health['max_stock'])
inventory_health['CAUTION_current_stock_unreliable'].value_counts()

CAUTION_current_stock_unreliable
True    180
Name: count, dtype: int64

In [25]:
### Data Quality Flag: current_stock Anomaly

##Issue:
#'current_stock' values are implausibly large relative to 'max_stock' across the entire dataset - not isolated rows.

##Evidence:
#'current_stock' range: 88853 - 121013 (avg ~107240)
#'max_stock' range: 131 - 582 (avg ~322)
#100% of rows (180/180) have 'current_stock > max_stock'

##Likely cause:
# Units mismatch or data-generation error - no warehouse realistically holds 100,000+ units against a stated capacity of ~500.

##Action taken:
# Flagged via 'CAUTION_current_stock_unreliable' column rather than silently corrected. Does **not** affect other columns (opening_stock, reorder_level, safety_stock, max_stock all fall within plausible ranges).

##Decision needed from team:
# Should 'current_stock' be corrected with an assumed scale factor, excluded from analysis, or is there a source-data explanation the team is aware of? Do not build stockout/overstock KPIs on this column until resolved.

In [26]:
inventory_health.duplicated().sum()

np.int64(0)

In [27]:
import re

str_cols = inventory_health.select_dtypes(include='object').columns

inventory_health[str_cols] = inventory_health[str_cols].apply(
    lambda x: x.str.replace(r'[\x00-\x1f\x7f]', '', regex=True)   # CLEAN: strip non-printable chars
                .str.replace(r'\s+', ' ', regex=True)               # collapse multiple spaces to one
                .str.strip()                                        # TRIM: remove leading/trailing space
)

inventory_health.sample(10)

,product_id,branch_id,opening_stock,reorder_level_inv,safety_stock_inv,max_stock,current_stock,warehouse_bin,product_name,category,...,region,warehouse_type,warehouse_capacity,service_center_available,manager_id,total_employees,avg_monthly_revenue,monthly_operational_cost,market_demand_index,CAUTION_current_stock_unreliable
91,P016,PUN001,217,74,47,371,103006,A07,Radiator RD-250,Cooling,...,West,Regional,38750 sqft,Yes,6114,74,4389120,2654000,8,True
60,P011,DEL001,243,85,64,369,112300,B01,Hydraulic Cylinder HC-200,Hydraulic,...,North,Central,45230 sqft,Yes,9593,92,5234890,3189000,9,True
161,P027,AHM001,151,51,33,294,108337,F10,O-Ring Set OR-50,Seals,...,West,Service Hub,34120 sqft,Yes,4772,63,3245890,2018000,7,True
76,P013,KOL001,129,44,26,233,105381,F03,Seal Kit SK-15,Seals,...,East,Branch,29880 sqft,No,5981,49,2894770,1743000,6,True
113,P019,AHM001,217,85,46,378,105387,A03,Swing Motor SWM-350,Hydraulic,...,West,Service Hub,34120 sqft,Yes,4772,63,3245890,2018000,7,True
23,P004,AHM001,273,104,77,430,99909,C08,Track Chain TC-45,Undercarriage,...,West,Service Hub,34120 sqft,Yes,4772,63,3245890,2018000,7,True
149,P025,AHM001,165,64,44,328,97512,F08,Cabin Glass CG-20,Cabin,...,West,Service Hub,34120 sqft,Yes,4772,63,3245890,2018000,7,True
127,P022,PUN001,299,119,60,487,111353,B16,Control Valve CV-75,Hydraulic,...,West,Regional,38750 sqft,Yes,6114,74,4389120,2654000,8,True
93,P016,HYD001,103,35,24,177,106040,A01,Radiator RD-250,Cooling,...,South,Branch,36210 sqft,No,4390,57,3102455,1887000,7,True
92,P016,CHN001,180,71,45,309,112003,C19,Radiator RD-250,Cooling,...,South,Regional,41890 sqft,Yes,7922,81,4567780,2739000,8,True

In [28]:
inventory_health.to_csv('inventory_health_master.csv', index=False)

In [29]:
## Second master table join - Stock_movement_master_table
data['stock_ledger'].columns
stock_movement = data['stock_ledger'].merge(data['products'][['product_id', 'product_name', 'category', 'criticality_level']], on = 'product_id')
stock_movement = stock_movement.merge(data['branches'][['branch_id', 'branch_name', 'region']], on = 'branch_id')
stock_movement.shape

(237230, 14)

In [30]:
stock_movement.head()

,movement_id,product_id,branch_id,movement_type,movement_date,quantity,reference_type,reference_id,running_balance,product_name,category,criticality_level,branch_name,region
0,MOV-OUT-184742,P001,AHM001,OUT,2019-01-03,8,SO,SO-157767,228,Hydraulic Pump HP-300,Hydraulic,High,Ahmedabad West Hub,West
1,MOV-OUT-208422,P001,AHM001,OUT,2019-01-05,12,SO,SO-168735,216,Hydraulic Pump HP-300,Hydraulic,High,Ahmedabad West Hub,West
2,MOV-IN-111128,P001,AHM001,IN,2019-01-23,174,PO,PO-181094,390,Hydraulic Pump HP-300,Hydraulic,High,Ahmedabad West Hub,West
3,MOV-OUT-159140,P001,AHM001,OUT,2019-01-25,12,SO,SO-947377,378,Hydraulic Pump HP-300,Hydraulic,High,Ahmedabad West Hub,West
4,MOV-OUT-173693,P001,AHM001,OUT,2019-01-25,11,SO,SO-879896,367,Hydraulic Pump HP-300,Hydraulic,High,Ahmedabad West Hub,West

In [31]:
stock_movement.sample(10)

,movement_id,product_id,branch_id,movement_type,movement_date,quantity,reference_type,reference_id,running_balance,product_name,category,criticality_level,branch_name,region
151447,MOV-OUT-158993,P020,AHM001,OUT,2021-12-22,1,SO,SO-790971,54225,Pivot Pin PP-12,Pins & Bushes,Medium,Ahmedabad West Hub,West
227144,MOV-IN-104967,P029,KOL001,IN,2020-11-08,170,PO,PO-326273,33944,Pressure Sensor PS-90,Sensors,Medium,Kolkata East Depot,East
146984,MOV-IN-49863,P019,DEL001,IN,2024-08-10,146,PO,PO-694717,109491,Swing Motor SWM-350,Hydraulic,High,Delhi Central,North
122755,MOV-OUT-240070,P016,DEL001,OUT,2022-11-23,14,SO,SO-949630,68144,Radiator RD-250,Cooling,Medium,Delhi Central,North
202962,MOV-IN-76135,P026,HYD001,IN,2024-02-25,292,PO,PO-335527,92598,Grease Cartridge GC-5,Lubricants,Low,Hyderabad Logistics,South
148481,MOV-OUT-195531,P019,KOL001,OUT,2020-03-17,13,SO,SO-601817,16925,Swing Motor SWM-350,Hydraulic,High,Kolkata East Depot,East
155500,MOV-OUT-158856,P020,HYD001,OUT,2022-08-11,17,SO,SO-343164,59728,Pivot Pin PP-12,Pins & Bushes,Medium,Hyderabad Logistics,South
81152,MOV-OUT-227911,P011,CHN001,OUT,2021-05-08,13,SO,SO-797144,41133,Hydraulic Cylinder HC-200,Hydraulic,High,Chennai South Hub,South
196931,MOV-OUT-241522,P025,PUN001,OUT,2020-07-14,20,SO,SO-278376,26520,Cabin Glass CG-20,Cabin,Medium,Pune Distribution,West
115267,MOV-OUT-177371,P015,DEL001,OUT,2024-10-05,7,SO,SO-120433,95504,Engine Block EB-600,Engine,High,Delhi Central,North

In [32]:
import re

str_cols = stock_movement.select_dtypes(include='object').columns

stock_movement[str_cols] = stock_movement[str_cols].apply(
    lambda x: x.str.replace(r'[\x00-\x1f\x7f]', '', regex=True)   # CLEAN: strip non-printable chars
                .str.replace(r'\s+', ' ', regex=True)               # collapse multiple spaces to one
                .str.strip()                                        # TRIM: remove leading/trailing space
)

stock_movement.sample(10)

,movement_id,product_id,branch_id,movement_type,movement_date,quantity,reference_type,reference_id,running_balance,product_name,category,criticality_level,branch_name,region
67006,MOV-IN-2073,P009,DEL001,IN,2023-04-06,275,PO,PO-693713,71970,Starter Motor SM-700,Electrical,High,Delhi Central,North
143800,MOV-IN-118761,P019,AHM001,IN,2022-09-30,204,PO,PO-147575,65083,Swing Motor SWM-350,Hydraulic,High,Ahmedabad West Hub,West
121290,MOV-OUT-233122,P016,CHN001,OUT,2022-07-25,3,SO,SO-791529,67511,Radiator RD-250,Cooling,Medium,Chennai South Hub,South
189411,MOV-IN-103168,P024,PUN001,IN,2022-09-20,232,PO,PO-749619,66743,Track Roller TR-60,Undercarriage,High,Pune Distribution,West
200876,MOV-OUT-257167,P026,DEL001,OUT,2020-03-23,11,SO,SO-847460,19480,Grease Cartridge GC-5,Lubricants,Low,Delhi Central,North
100745,MOV-OUT-158882,P013,KOL001,OUT,2019-06-19,5,SO,SO-690298,7982,Seal Kit SK-15,Seals,Medium,Kolkata East Depot,East
40522,MOV-OUT-186801,P006,AHM001,OUT,2023-02-28,19,SO,SO-917351,76880,Alternator ALT-500,Electrical,High,Ahmedabad West Hub,West
208473,MOV-IN-6456,P027,CHN001,IN,2025-01-05,133,PO,PO-902728,97102,O-Ring Set OR-50,Seals,Low,Chennai South Hub,South
57291,MOV-IN-120381,P008,CHN001,IN,2020-04-24,226,PO,PO-472042,26291,Bucket Tooth BT-10,Attachments,Low,Chennai South Hub,South
15698,MOV-IN-92311,P002,PUN001,IN,2024-05-19,173,PO,PO-641532,91386,Engine Oil Filter OF-90,Filters,Medium,Pune Distribution,West

In [33]:
stock_movement.isnull().sum()

movement_id          0
product_id           0
branch_id            0
movement_type        0
movement_date        0
quantity             0
reference_type       0
reference_id         0
running_balance      0
product_name         0
category             0
criticality_level    0
branch_name          0
region               0
dtype: int64

In [34]:
stock_movement.duplicated().sum()

np.int64(0)

In [36]:
stock_movement.describe()

            quantity  running_balance
count  237230.000000    237230.000000
mean       91.007111     53439.071268
std        95.276281     31093.025775
min         1.000000        14.000000
25%        11.000000     26531.000000
50%        40.000000     53240.500000
75%       170.000000     80015.000000
max       300.000000    121013.000000

In [37]:
stock_movement.to_csv('stock_movement_master.csv', index=False)